# Workflow name shown in the GitHub Actions
name: "Build and Push to GHCR"

# Trigger the workflow when pushing a tag like: v1.0.0
on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]"

# Set environment variables available to all steps
env:
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }} # GitHub Container Registry token (set in repository secrets)
  # CONTAINER_NAME # Image name to publish (all lowercase)
  # USER_NAME # GitHub username used for GHCR authentication

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Step 1
      - name: Set up checkout
        uses: actions/checkout@v4

      # Step 2
      - name: Set up latest git tag
        run: |
          RAW_TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${RAW_TAG#*@}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version: $VERSION"

      - name: Set up variables
        shell: bash
        run: |
          CONTAINER_NAME=${GITHUB_REPOSITORY,,}
          echo "CONTAINER_NAME=${CONTAINER_NAME}" >> $GITHUB_ENV
          echo "Container name: $CONTAINER_NAME"
          USER_NAME=${CONTAINER_NAME%%/*}
          echo "USER_NAME=${USER_NAME}" >> $GITHUB_ENV
          echo "User name: $USER_NAME"

      # --- Build Stage ---

      # Step 3
      - name: Docker build
        run: |
          docker build -t ghcr.io/${{ env.CONTAINER_NAME }}:latest .
          docker build -t ghcr.io/${{ env.CONTAINER_NAME }}:${{ env.VERSION }} .

      # --- Push Stage ---

      # Step 4
      - name: GitHub (GHCR) login
        run: echo $GHCR_TOKEN | docker login ghcr.io -u $USER_NAME --password-stdin

      # Step 5
      - name: GitHub (GHCR) push
        run: |
          docker push ghcr.io/${{ env.CONTAINER_NAME }}:latest
          docker push ghcr.io/${{ env.CONTAINER_NAME }}:${{ env.VERSION }}
